package com.prospr.controller;
import com.prospr.dto.FamilyMemberResponse; import com.prospr.model.*; import com.prospr.repository.*; import com.prospr.service.HouseholdAccess; import java.security.*; import java.time.*; import java.util.*; import org.springframework.beans.factory.annotation.Value; import org.springframework.http.*; import org.springframework.security.core.annotation.AuthenticationPrincipal; import org.springframework.web.bind.annotation.*; import org.springframework.web.server.ResponseStatusException;

@RestController @RequestMapping("/api") @CrossOrigin(origins="${PROSPR_WEB_ORIGIN:http://localhost:3000}")
public class HouseholdController {
  private final FamilyMemberRepository families; private final FinancialAccountRepository accounts; private final GoalRepository goals; private final BudgetRepository budgets; private final HouseholdAccess access; private final String webOrigin;
  public HouseholdController(FamilyMemberRepository f, FinancialAccountRepository a, GoalRepository g, BudgetRepository b, HouseholdAccess access, @Value("${PROSPR_WEB_ORIGIN:http://localhost:3000}") String webOrigin){families=f;accounts=a;goals=g;budgets=b;this.access=access;this.webOrigin=webOrigin.replaceAll("/$","");}
  @GetMapping("/family-members") public List<FamilyMemberResponse> family(@AuthenticationPrincipal String account){return families.findByHouseholdId(access.householdId(account)).stream().map(FamilyMemberResponse::roster).toList();}
  @PostMapping("/family-members") public FamilyMemberResponse addFamily(@AuthenticationPrincipal String account,@RequestBody FamilyMember item){access.requireCreator(account); if(item.username==null||!item.username.matches("[A-Za-z0-9._-]{3,40}"))throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"Username must be 3-40 letters, numbers, dots, underscores, or hyphens."); item.id=null;item.ownerId=account;item.householdId=access.householdId(account);item.username=item.username.toLowerCase(Locale.ROOT);item.status="PENDING";String link=issueLink(item);families.save(item);return FamilyMemberResponse.issued(item,link);}
  @PostMapping("/family-members/{id}/activation-link") public FamilyMemberResponse newLink(@AuthenticationPrincipal String account,@PathVariable String id){access.requireCreator(account);FamilyMember item=families.findById(id).orElseThrow();owned(item,access.householdId(account));if("ACTIVE".equals(item.status))throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"Active members cannot use an activation link.");String link=issueLink(item);families.save(item);return FamilyMemberResponse.issued(item,link);}
  @PutMapping("/family-members/{id}") public FamilyMemberResponse updateFamily(@AuthenticationPrincipal String account,@PathVariable String id,@RequestBody FamilyMember item){access.requireCreator(account);FamilyMember old=families.findById(id).orElseThrow();owned(old,access.householdId(account));item.id=id;item.ownerId=old.ownerId;item.householdId=old.householdId;item.accountId=old.accountId;item.status=old.status;item.activationTokenHash=old.activationTokenHash;item.activationExpiresAt=old.activationExpiresAt;item.activationExpiryEpoch=old.activationExpiryEpoch;item.updatedAt=LocalDateTime.now();return FamilyMemberResponse.roster(families.save(item));}
  @DeleteMapping("/family-members/{id}") @ResponseStatus(HttpStatus.NO_CONTENT) public void deleteFamily(@AuthenticationPrincipal String account,@PathVariable String id){access.requireCreator(account);FamilyMember x=families.findById(id).orElseThrow();owned(x,access.householdId(account));if(x.id.equals(access.user(account).getMemberId()))throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"The household creator cannot remove their own account.");families.delete(x);}
  @GetMapping("/financial-accounts") public List<FinancialAccount> accounts(@AuthenticationPrincipal String account){return accounts.findByHouseholdId(access.householdId(account));}
  @PostMapping("/financial-accounts") public FinancialAccount addAccount(@AuthenticationPrincipal String account,@RequestBody FinancialAccount item){item.id=null;item.ownerId=account;item.householdId=access.householdId(account);return accounts.save(item);}
  @GetMapping("/goals") public List<Goal> goals(@AuthenticationPrincipal String account){return goals.findByHouseholdId(access.householdId(account));}
  @PostMapping("/goals") public Goal addGoal(@AuthenticationPrincipal String account,@RequestBody Goal item){item.id=null;item.ownerId=account;item.householdId=access.householdId(account);return goals.save(item);}
  @PutMapping("/goals/{id}") public Goal updateGoal(@AuthenticationPrincipal String account,@PathVariable String id,@RequestBody Goal item){Goal x=goals.findById(id).orElseThrow();owned(x,access.householdId(account));item.id=id;item.ownerId=x.ownerId;item.householdId=x.householdId;return goals.save(item);}
  @DeleteMapping("/goals/{id}") @ResponseStatus(HttpStatus.NO_CONTENT) public void deleteGoal(@AuthenticationPrincipal String account,@PathVariable String id){Goal x=goals.findById(id).orElseThrow();owned(x,access.householdId(account));goals.delete(x);}
  @GetMapping("/budgets") public List<Budget> budgets(@AuthenticationPrincipal String account){return budgets.findByHouseholdId(access.householdId(account));}
  @PostMapping("/budgets") public Budget addBudget(@AuthenticationPrincipal String account,@RequestBody Budget item){item.id=null;item.ownerId=account;item.householdId=access.householdId(account);return budgets.save(item);}
  @PutMapping("/budgets/{id}") public Budget updateBudget(@AuthenticationPrincipal String account,@PathVariable String id,@RequestBody Budget item){Budget x=budgets.findById(id).orElseThrow();owned(x,access.householdId(account));item.id=id;item.ownerId=x.ownerId;item.householdId=x.householdId;return budgets.save(item);}
  @DeleteMapping("/budgets/{id}") @ResponseStatus(HttpStatus.NO_CONTENT) public void deleteBudget(@AuthenticationPrincipal String account,@PathVariable String id){Budget x=budgets.findById(id).orElseThrow();owned(x,access.householdId(account));budgets.delete(x);}
  private void owned(Object item,String household){String value=item instanceof FamilyMember x?x.householdId:item instanceof Goal x?x.householdId:item instanceof Budget x?x.householdId:null;if(!household.equals(value))throw new ResponseStatusException(HttpStatus.FORBIDDEN);}
  private String issueLink(FamilyMember item){String raw=UUID.randomUUID()+"."+UUID.randomUUID();item.activationTokenHash=hash(raw);item.activationExpiresAt=LocalDateTime.now().plusDays(7);item.activationExpiryEpoch=System.currentTimeMillis()+7L*24*60*60*1000;return webOrigin+"/activate?token="+raw;}
  private String hash(String raw){try{return HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(raw.getBytes(java.nio.charset.StandardCharsets.UTF_8)));}catch(Exception e){throw new IllegalStateException(e);}}
}
